version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: ecommerce-db
    restart: always
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - ecommerce-network
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: ecommerce-app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ecommerce
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - ecommerce-network

volumes:
  db_data:

networks:
  ecommerce-network: