server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: mutation-testing-with-maven

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate